name: RiskAnalysis
dependencies:
  - django
  - pymongo
  - pip
  - pip:
      - tweepy
      - cryptography==3.0
      - djongo==1.3.3
      - djangorestframework==3.11.0
      - django-cors-headers==3.4.0

